### ISSUE TITLE
<strong> isn't bold

### ISSUE THREAD

**Issue by garretwilson** [milligram/milligram#131]
Wow, I just realized that `<strong>` doesn't get bold by default. In fact it doesn't seem to have any style.

I'm about to give up on Milligram for a "reasonable defaults out of the box" CSS library. I welcome recommendations for something else.

Take for example the following HTML5 file:

```html
<!DOCTYPE html>
<html lang="en-US">

<head>
	<title>Milligram Strong Bug</title>
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic">
	<link rel="stylesheet" href="css/normalize.css">
	<link rel="stylesheet" href="css/milligram.min.css">
</head>

<body>
	<p>This paragraph should have <strong>strong</strong> text.</p>
	<p>This paragraph should have <b>bold</b> text.</p>
</body>

</html>
```

Obviously, substitute your own paths for your local Normalize and Milligram copies. (I didn't see any CDN URLs for Milligram or I would have used them in this example.)

Now open it up in Chrome or Firefox (the two browsers I tested this in). You'll see that there is no bold text. There should be.

The cause? This gets interesting. It looks like `normalize.css` is setting the `font-weight` to `bolder`. But it doesn't show up. Changing this to `bold` makes the bold show up.

The problem seems to be that the Roboto font doesn't support varying degrees of bold.

(At first I said to see http://stackoverflow.com/q/39405766/421049 , but that reference looks unrelated --- although that is a different different issue that presents a problem.)

`normalize.css` is technically correct in that semantically the value `bolder` is better in this case. See https://www.w3.org/Bugs/Public/show_bug.cgi?id=12154

However because Milligram _knows_ that it is using a font that doesn't support varying degrees of bolder, I think that you must override `normalize.css` and use `bold` unless you have a better idea. Otherwise if the font does not show up in bold this is a Milligram --- even if you claim that it's Roboto's fault (and it may be).

That's my opinion at the moment until presented with a better explanation. 😄

**Comment by cjpatoilo** [comment]
Hi @garretwilson

You need to report something so I can analyze this problem that is happening to you. Check the [documentation](https://github.com/milligram/milligram/blob/master/.github/contributing.md#open-an-issue), it can guide you to pass the necessary information.

I'm waiting for you

**Comment by garretwilson** [comment]
> You need to report something...

Um, I thought I just did. `<strong>` doesn't have any style by default.

**Comment by garretwilson** [comment]
I'll update the description if it isn't clear. But... I think it is clear.

**Comment by cjpatoilo** [comment]
@garretwilson You can use our [Issue Template](https://github.com/milligram/milligram/blob/master/.github/issue_template.md) for this

**Comment by garretwilson** [comment]
I've updated the description. You should have everything you need now.

**Comment by sudheerDev** [comment]
@garretwilson you dont need a CDN link!! all you need is a link to css file!! So, anyway here it is
https://raw.githubusercontent.com/milligram/milligram/master/dist/milligram.css.

Who said roboto dosent have bold, bolder font-weights? 

https://fonts.google.com/specimen/Roboto?selection.family=Roboto:400,400i,500,500i,700,700i,900,900i

And it does work on milligram webpage 
<img width="1302" alt="screen shot 2016-12-01 at 16 18 17" src="https://cloud.githubusercontent.com/assets/4973621/20791206/de6adcc6-b7e1-11e6-813d-29a95e40ffd3.png">

**Comment by sudheerDev** [comment]
@garretwilson you dont need a CDN link!! all you need is a link to css file!! So, anyway here it is
https://raw.githubusercontent.com/milligram/milligram/master/dist/milligram.css.

Who said roboto dosent have bold, bolder font-weights? 

https://fonts.google.com/specimen/Roboto?selection.family=Roboto:400,400i,500,500i,700,700i,900,900i

And it does work on milligram webpage 

<img width="1440" alt="screen shot 2016-12-01 at 16 21 55" src="https://cloud.githubusercontent.com/assets/4973621/20791317/547f6e86-b7e2-11e6-9013-a377328bf068.png">
<img width="1440" alt="screen shot 2016-12-01 at 16 21 48" src="https://cloud.githubusercontent.com/assets/4973621/20791326/6206e868-b7e2-11e6-9db9-d845cab960f1.png">

**Comment by cjpatoilo** [comment]
Hey @garretwilson @sudheerDev I fixed this issue. Basically it was a change in the normalize that broke the Milligram. Thank you very much for your attention.

For now I'll close this issue. Feel free to reopen this issue if this doesn't do the trick for you.

**Comment by garretwilson** [comment]
> Who said roboto dosent have bold, bolder font-weights?
> https://fonts.google.com/specimen/Roboto?selection.family=Roboto:400,400i,500,500i,700,700i,900,900i

I was making a best guess about the problem. If Roboto supports varying degrees of bold, that's great. But it looks like @cjpatoilo's solution was to simply overrides `<strong>` to make it `bold` instead of `bolder`.

So @sudheerDev , if Roboto supports `bolder`, maybe you could explain to us why it isn't working in the example I provided, and what @cjpatoilo can do to make `bolder` work instead of changing it to `bold`.

**Comment by sudheerDev** [comment]
@garretwilson here is a [fiddle](https://jsfiddle.net/1240obpk/2/) with the described scenario. 

I commented the lines @cjpatoilo recently added i.e adding `bold` lines- 528-531. you can still that the font-weight for `strong` and `b` is different from the normal text. 

problem from what i see is that it is not that bolder and the reason being 

     
      body {
        color: #606c76;
        font-family: 'Roboto', 'Helvetica Neue', 'Helvetica', 'Arial', sans-serif;
        font-size: 1.6em;
        font-weight: 300;
        letter-spacing: .01em;
        line-height: 1.6;
     }
  
remove `font-weight:300` from body declaration and see. You would notice the difference and see that bolder property working fine. The effect of having font-weight declared on body will be different for different fonts.

**Comment by garretwilson** [comment]
This is very interesting and I hope to learn something from it. Thanks for the explanation, @sudheerDev . So you're saying that by declaring a `font-weight` on the `<body>` (this is part of `normalize.css`?), somehow it makes `bolder` stop working for `Roboto`? That's very good to know, but I'm still not sure _why_.

Should I file a Stack Overflow question to get more details? It seems like the problem goes deeper than Milligram. Wherever the problem lies, the `normalize.css` and/or `Roboto` might need/want to know about it.

**Comment by sudheerDev** [comment]
@garretwilson Let me see if i can shed more light on this. If its not that clear feel free to post a question on stack overflow.

    normal
     Normal font weight. Same as 400.
    bold
     Bold font weight. Same as 700.
    lighter
     One font weight lighter than the parent element (among the available weights of the font).
    bolder
     One font weight darker than the parent element (among the available weights of the font).

If you have `font-weight: 300` set on body. Then bolder will be 400 because bolder is relative to the inherited font-weight i.e 300. 

Where as bold is absolute to 700 so you have that applied seeing a really bolder version of the font and that is the fix that @cjpatoilo added today [commit](https://github.com/milligram/milligram/commit/905870176f6294111335e6f02fb8a6f8acea1c83)

Normalize.css adds bolder because it respects your font-weight and adding just 100 weight to it. changing that with milligram is slighly questionable by using bold. 

Milligram by default keeps your body font-weight low so if you like having a lighter font-weight use the default or just override in your codebase with

     body {
       font-weight: normal;
     }

**Comment by garretwilson** [comment]
> If you have `font-weight: 300` set on body. Then bolder will be 400 because bolder is relative to the inherited font-weight i.e 300.

Yeah, I got that, and it makes perfect sense. But I guess what is confusing me is: shouldn't it still appear "bolder", because 400 is a higher weight than 300? Is the problem that Roboto doesn't support 400 vs 300, or is the problem that my monitor can't show the difference, or is the problem that my eyes can't see the difference?

**Comment by sudheerDev** [comment]
<img width="1134" alt="screen shot 2016-12-01 at 23 40 48" src="https://cloud.githubusercontent.com/assets/4973621/20806122/a0fd9930-b81f-11e6-93ad-0e2009858be4.png">

check the image above. I do see a difference in weights.

**Comment by garretwilson** [comment]
![milligram-strong-bug](https://cloud.githubusercontent.com/assets/627125/20807158/6498cd04-b7c3-11e6-8c07-fb336dc31dba.png)

This is very odd. Look at my screen shot in Chrome (even magnified using the Magnifier in Windows 10). I see no difference at all.

Could it be something to do with how you are including the Roboto font? What link are you using, with which URL query parameters?

**Comment by sudheerDev** [comment]
Thats odd!. https://jsfiddle.net/1240obpk/4/ updated link for fiddle with all the font-weights. 

https://fonts.google.com/specimen/Roboto?selection.family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i

**Comment by garretwilson** [comment]
That is very odd indeed. I tried the Roboto link you gave and it makes no difference for me. I still have no difference in font weight. I thought maybe the old Roboto was being cached (from the link I used from the Milligram web site instructions), so I brought up @sudheerDev's jsfiddle page above in Microsoft Edge --- but I don't see any difference there either. I'm perplexed.

**Comment by garretwilson** [comment]
OK _now_ we're getting somewhere, and this is starting to make sense.

First of all, @sudheerDev , when I asked for the link you are using, I meant the link to the font's CSS to use in your HTML file, but you gave me the link to the font's _web page_. On that web page you have to generate a link to use as a stylesheet; it gives me https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i and you use it like this:

```html
<link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i" rel="stylesheet">
```

When I use _that_, then yes, I see the difference between a weight of `300` and `400`!! It's not a big difference, but it's exactly what I would expect.

When I encountered the problem, I was following the instruction on the Milligram "Getting Started" page https://milligram.github.io/#getting-started, which says to use this link:

```html
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic">
```

@sudheerDev I recommend you try that link and you'll likely see the same results I was seeing. I need to research what the query parameters mean.

But in any case, the real problem seems to be the erroneous link on the Milligram web page. It doesn't bring in sufficient variations of the font to use with Milligram. The `normalize.css` setting of `bolder` was more correct.

@cjpatoilo , I _highly_ recommend that you undo your change to `font-weight: bold`, because turned out to be sort of a kludge covering up the real problem: I was using an incompatible link to the Roboto font. **The _real_ fix for this issue is to update the Milligram web site to indicate a compatible link to the Roboto font.** Make sense?

**Comment by cjpatoilo** [comment]
Hey @garretwilson @sudheerDev 

If you're thinking of just using Roboto for every project, yes, it makes sense. But there are other projects that do not make use of Roboto as main font family. Other font families does not have the same support that this family provides. Also do not forget perf. It will be slower than currently if we add more font weights.

Anyway, it's a great discussion. It pays to make more tests to make the best decision about this change.

**Comment by garretwilson** [comment]
> But there are other projects that do not make use of Roboto as main font family.

I don't understand what you're proposing. You're already showing Roboto on the "get started" page. We just need to change it to a Roboto that works with `bolder`. If they don't use Roboto... well, they probably won't run into this problem to begin with. The problem only occurred because the get-started example limited Roboto. Fix that and the problem is fixed.

Why force `bold`, breaking the elegance of `normalize.css`, when all you need to do is fix the example?

**Comment by chmln** [comment]
> I don't know what "perf"

Performance.

@cjpatoilo I think the 'right' solution would be to have `body` with `font-weight: 400`, i.e. not overriding the default `font-weight`.

That will:
1. Make `bolder`, `lighter` font properties function correctly
2. Provide better typography. Light fonts are an eye strain, and lack readability. (see comparison below)

![light](https://cloud.githubusercontent.com/assets/11352152/21199678/82034b36-c212-11e6-8c3b-d9f84ce6e933.png)
![regular](https://cloud.githubusercontent.com/assets/11352152/21199680/841bb23c-c212-11e6-9d6c-a24165eb83bb.png)

**Comment by nateberkopec** [comment]
[Worth consulting this table on MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight) - a default font-weight:400 greatly changes the behavior of `bolder` and `lighter`:

![screen shot 2016-12-14 at 1 52 55 pm](https://cloud.githubusercontent.com/assets/845662/21200491/a216d0a4-c204-11e6-8f33-21d58e512c3a.png)

In addition, a font-weight setting of 300 has a very different fallback behavior than font-weight 400 if the user does not have the 300-weight font downloaded/available:

![screen shot 2016-12-14 at 1 56 23 pm](https://cloud.githubusercontent.com/assets/845662/21200597/208fb95a-c205-11e6-8cf0-a52966d51af1.png)

In short, for 300 weight, bolder is 400 and lighter is 100. If the font selected does not have 300-weight downloaded/available, the browser will try one step *lighter* - 200, and so on, until it finds a weight the user has available.

For 400 weight, bolder is 700 and lighter is 100. If the font selected does not have a 400 weight font available (unlikely, because 400 is "normal"), the browser will try weight 500.

As I think has been adequately discussed above, unlike a straight-up font-weight declaration, `bolder` and `lighter` will not attempt to fallback to a different weight if the required weight is not available.

Many fonts don't have a 300 weight defined, which means Milligram can interact poorly with those fonts because it may select a very inappropriately thin font if it is available (worst case would be a font with only 100 and 400 weights defined). Of course, this can also be caused by the webpage not downloading all the correct widths of the font (Google Fonts, etc).

I understand that Milligram is trying to make a stylistic choice by making the default font a "thin" weight, but it may be causing more problems than is worth it.

**Comment by ItsPugle** [comment]
I believe this issue can be closed? The `<strong>` tag now produces a much bolder text than text without:
![image](https://user-images.githubusercontent.com/22669894/60383232-b058a880-9ab1-11e9-89d7-73ac481260fe.png)
https://test.itspugle.com/milligram/strong
